/* This file was generated by SableCC (http://www.sablecc.org/). */

package cminus.node;

import cminus.analysis.*;

@SuppressWarnings("nls")
public final class AExprLogicaExpr extends PExpr
{
    private PExprLogica _exprLogica_;

    public AExprLogicaExpr()
    {
        // Constructor
    }

    public AExprLogicaExpr(
        @SuppressWarnings("hiding") PExprLogica _exprLogica_)
    {
        // Constructor
        setExprLogica(_exprLogica_);

    }

    @Override
    public Object clone()
    {
        return new AExprLogicaExpr(
            cloneNode(this._exprLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprLogicaExpr(this);
    }

    public PExprLogica getExprLogica()
    {
        return this._exprLogica_;
    }

    public void setExprLogica(PExprLogica node)
    {
        if(this._exprLogica_ != null)
        {
            this._exprLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprLogica_ == child)
        {
            this._exprLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprLogica_ == oldChild)
        {
            setExprLogica((PExprLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
