/* This file was generated by SableCC (http://www.sablecc.org/). */

package cminus.node;

import cminus.analysis.*;

@SuppressWarnings("nls")
public final class AExprAritimeticaExpr extends PExpr
{
    private PExprAritimetica _exprAritimetica_;

    public AExprAritimeticaExpr()
    {
        // Constructor
    }

    public AExprAritimeticaExpr(
        @SuppressWarnings("hiding") PExprAritimetica _exprAritimetica_)
    {
        // Constructor
        setExprAritimetica(_exprAritimetica_);

    }

    @Override
    public Object clone()
    {
        return new AExprAritimeticaExpr(
            cloneNode(this._exprAritimetica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprAritimeticaExpr(this);
    }

    public PExprAritimetica getExprAritimetica()
    {
        return this._exprAritimetica_;
    }

    public void setExprAritimetica(PExprAritimetica node)
    {
        if(this._exprAritimetica_ != null)
        {
            this._exprAritimetica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprAritimetica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprAritimetica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprAritimetica_ == child)
        {
            this._exprAritimetica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprAritimetica_ == oldChild)
        {
            setExprAritimetica((PExprAritimetica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
