/* This file was generated by SableCC (http://www.sablecc.org/). */

package cminus.node;

import java.util.*;
import cminus.analysis.*;

@SuppressWarnings("nls")
public final class AInstrucoesCompostas extends PInstrucoesCompostas
{
    private final LinkedList<PDeclaracao> _declaracao_ = new LinkedList<PDeclaracao>();
    private final LinkedList<PInstrucao> _instrucao_ = new LinkedList<PInstrucao>();

    public AInstrucoesCompostas()
    {
        // Constructor
    }

    public AInstrucoesCompostas(
        @SuppressWarnings("hiding") List<?> _declaracao_,
        @SuppressWarnings("hiding") List<?> _instrucao_)
    {
        // Constructor
        setDeclaracao(_declaracao_);

        setInstrucao(_instrucao_);

    }

    @Override
    public Object clone()
    {
        return new AInstrucoesCompostas(
            cloneList(this._declaracao_),
            cloneList(this._instrucao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrucoesCompostas(this);
    }

    public LinkedList<PDeclaracao> getDeclaracao()
    {
        return this._declaracao_;
    }

    public void setDeclaracao(List<?> list)
    {
        for(PDeclaracao e : this._declaracao_)
        {
            e.parent(null);
        }
        this._declaracao_.clear();

        for(Object obj_e : list)
        {
            PDeclaracao e = (PDeclaracao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declaracao_.add(e);
        }
    }

    public LinkedList<PInstrucao> getInstrucao()
    {
        return this._instrucao_;
    }

    public void setInstrucao(List<?> list)
    {
        for(PInstrucao e : this._instrucao_)
        {
            e.parent(null);
        }
        this._instrucao_.clear();

        for(Object obj_e : list)
        {
            PInstrucao e = (PInstrucao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._instrucao_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracao_)
            + toString(this._instrucao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracao_.remove(child))
        {
            return;
        }

        if(this._instrucao_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDeclaracao> i = this._declaracao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclaracao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PInstrucao> i = this._instrucao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PInstrucao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
