/* This file was generated by SableCC (http://www.sablecc.org/). */

package cminus.node;

import cminus.analysis.*;

@SuppressWarnings("nls")
public final class AIntTipo extends PTipo
{
    private TKwInt _kwInt_;

    public AIntTipo()
    {
        // Constructor
    }

    public AIntTipo(
        @SuppressWarnings("hiding") TKwInt _kwInt_)
    {
        // Constructor
        setKwInt(_kwInt_);

    }

    @Override
    public Object clone()
    {
        return new AIntTipo(
            cloneNode(this._kwInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntTipo(this);
    }

    public TKwInt getKwInt()
    {
        return this._kwInt_;
    }

    public void setKwInt(TKwInt node)
    {
        if(this._kwInt_ != null)
        {
            this._kwInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwInt_ == child)
        {
            this._kwInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwInt_ == oldChild)
        {
            setKwInt((TKwInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
