/* This file was generated by SableCC (http://www.sablecc.org/). */

package cminus.node;

import cminus.analysis.*;

@SuppressWarnings("nls")
public final class AMainFunDeclaracao extends PDeclaracao
{
    private PInstrucoesCompostas _instrucoesCompostas_;

    public AMainFunDeclaracao()
    {
        // Constructor
    }

    public AMainFunDeclaracao(
        @SuppressWarnings("hiding") PInstrucoesCompostas _instrucoesCompostas_)
    {
        // Constructor
        setInstrucoesCompostas(_instrucoesCompostas_);

    }

    @Override
    public Object clone()
    {
        return new AMainFunDeclaracao(
            cloneNode(this._instrucoesCompostas_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMainFunDeclaracao(this);
    }

    public PInstrucoesCompostas getInstrucoesCompostas()
    {
        return this._instrucoesCompostas_;
    }

    public void setInstrucoesCompostas(PInstrucoesCompostas node)
    {
        if(this._instrucoesCompostas_ != null)
        {
            this._instrucoesCompostas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrucoesCompostas_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instrucoesCompostas_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instrucoesCompostas_ == child)
        {
            this._instrucoesCompostas_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instrucoesCompostas_ == oldChild)
        {
            setInstrucoesCompostas((PInstrucoesCompostas) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
