/* This file was generated by SableCC (http://www.sablecc.org/). */

package cminus.node;

import cminus.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorExprLogica extends PExprLogica
{
    private PExprAritimetica _first_;
    private PExprAritimetica _second_;

    public AMaiorExprLogica()
    {
        // Constructor
    }

    public AMaiorExprLogica(
        @SuppressWarnings("hiding") PExprAritimetica _first_,
        @SuppressWarnings("hiding") PExprAritimetica _second_)
    {
        // Constructor
        setFirst(_first_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorExprLogica(
            cloneNode(this._first_),
            cloneNode(this._second_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorExprLogica(this);
    }

    public PExprAritimetica getFirst()
    {
        return this._first_;
    }

    public void setFirst(PExprAritimetica node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public PExprAritimetica getSecond()
    {
        return this._second_;
    }

    public void setSecond(PExprAritimetica node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PExprAritimetica) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PExprAritimetica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
