/* This file was generated by SableCC (http://www.sablecc.org/). */

package cminus.node;

import cminus.analysis.*;

@SuppressWarnings("nls")
public final class AStringTipo extends PTipo
{
    private TKwString _kwString_;

    public AStringTipo()
    {
        // Constructor
    }

    public AStringTipo(
        @SuppressWarnings("hiding") TKwString _kwString_)
    {
        // Constructor
        setKwString(_kwString_);

    }

    @Override
    public Object clone()
    {
        return new AStringTipo(
            cloneNode(this._kwString_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringTipo(this);
    }

    public TKwString getKwString()
    {
        return this._kwString_;
    }

    public void setKwString(TKwString node)
    {
        if(this._kwString_ != null)
        {
            this._kwString_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwString_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwString_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwString_ == child)
        {
            this._kwString_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwString_ == oldChild)
        {
            setKwString((TKwString) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
